config/routes.rb
Rails.application.routes.draw do
  root 'players#index'

resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  end
  def new
  	@player = Player.new
  end
  def create
  	@player = Player.new(player_params)
    @player.save
redirect_to @player
  end
  def show
  	@player = Player.find(params[:id])
  end
  def edit
  	@player = Player.find(params[:id])
  end
  def update
  end
  def destroy
  end
  private
  def player_params
  	params.require(:player).permit(:nickname, :rank, :charisma, :wisdow)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player, url: player_path do |f| %>
<%= f.label :nickname %>
  <%= f.text_field :nickname %><br />
  <%= f.label :rank %> 
  <%= f.text_field :rank %><br />
  <%= f.label :charisma %>
  <%= f.text_field :charisma %><br />
  <%= f.label :wisdow %>
  <%= f.text_field :wisdow %><br />
            
  <%= f.submit "Create" %>
<% end %>

app/views/players/index.html.erb
<h1>This is my game</h1>
<%= link_to "Registration", new_player_path %>

app/views/players/new.html.erb
<%= form_for @player do |f| %>
<%= f.label :nickname %>
  <%= f.text_field :nickname %><br />
  <%= f.label :rank %> 
  <%= f.text_field :rank %><br />
  <%= f.label :charisma %>
  <%= f.text_field :charisma %><br />
  <%= f.label :wisdow %>
  <%= f.text_field :wisdow %><br />
            
  <%= f.submit "Create" %>
<% end %>

app/views/players/show.html.erb
<p>
	<strong>nickname</strong>
<%= @player.nickname %><br />
<strong>rank</strong>
<%= @player.rank %><br />
<strong>charisma</strong>
<%= @player.charisma %><br />
<strong>wisdow</strong>
<%= @player.wisdow %><br />
<%= link_to "Edit", edit_player_path %><br />
<%= link_to "Back", players_path %>

</p>